apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app : {{ .Values.fullnameOverride }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.containerPort | default 80 }}
